### ISSUE TITLE
As a customer I want to be able to log in to the system securely so I can access my account features.

### ISSUE THREAD

**Issue by KimmoKAhola** [KYH-Net23/AuthenticationService#11]
Authors: Kimmo Ahola & Isabel Haataja

# Acceptance Criteria:
- [ ] There needs to be a login button in the navbar.
- [ ] There needs to be a login form.
- [ ] There needs to be an authentication process to check credentials.
- [ ] There should be a remember me option for future login sessions (cookies).
- [ ] Customers should login with an email address and a password.

# Tasks:
- [ ] Task 1: Implement a “Login” button.
- [ ] Task 2: Implement a login form with input fields: Email Address and Password.
- [ ] Task 3: Implement ASP.NET CORE Identity
Identity User
Identity Role (Customer)
Password Rules
Cookie Rules
- [ ] Task 4: Implement a “Remember me” checkbox.

# Test Cases:
### Steps:
- [ ] Create a mock user
- [ ] Attempt to login using the correct email address but incorrect password.
### Expected Results: 
- [ ] The login fails and the account gets locked out.

### Prerequisites:
- [ ] “Remember me” checkbox is present
- [ ] User has valid credentials.
### Steps:
- [ ] Enter valid customer user credentials.
- [ ] Select the “Remember me” checkbox.
- [ ] Submit the form, press “Login”.
- [ ] Clear the browser to end the session.
- [ ] Reopen browser and reopen the application.
Expected Results: 
- [ ] The customer remains logged in.

### Steps:
- [ ] Create a mock user.
- [ ] Attempt to login with correct credentials.
### Expected Results:
- [ ] The user is logged in with a success message.

# Activity Diagram: ![Image](https://github.com/user-attachments/assets/a9f71b66-278e-4949-bd5b-b41355252284)
