### ISSUE TITLE
As an admin I want to be able to reset my password from the login page if I have forgotten it.

### ISSUE THREAD

**Issue by KimmoKAhola** [KYH-Net23/AuthenticationService#18]
Authors: Kimmo Ahola & Isabel Haataja

# Acceptance Criteria:
- [ ] There should be a form for entering the user’s email address.
- [ ] An email should be sent to the user, with a link to reset the password.
- [ ] There should be a form for entering the new password.
- [ ] After the new password has been created an email confirmation should be sent to the user’s email address.

# Tasks:
- [ ] Implement a “Forgot your password?” link to the Login page if there is not one yet.
- [ ] Implement a form with the field: email address.
- [ ] Implement a message that notifies the user to check their inbox.
- [ ] Implement a “Send reset link” button to the form that sends an email to the user.
- [ ] Implement a form with fields: password and repeat password.
- [ ] Implement a “Reset password” button to the form.
- [ ] Implement an EmailProvider.

# Test Cases:
### Expected Results:

# Activity Diagram:
