### ISSUE TITLE
As an admin I want to be able to log in to the system securely so that I can access administrative features and manage the application effectively.

### ISSUE THREAD

**Issue by KimmoKAhola** [KYH-Net23/AuthenticationService#2]
Authors: Kimmo Ahola & Isabel Haataja

# Acceptance Criteria:
- [ ] There needs to be a login button in the navbar.
- [ ] Customers and admins login on the same page.
- [ ] There needs to be a login form.
- [ ] There needs to be an authentication process to check credentials.
- [ ] There should be a remember me option for future login sessions (cookies).
- [ ] The admin should be locked out after 3 failed attempts if the password entered is incorrect but the email is correct.
- [ ] Admin should login with an email address and a password.

# Tasks:
- [ ] Task 1: Implement a “Login” button.
- [ ] Task 2: Implement a login form with input fields: Email Address and Password.
- [ ] Task 3: Implement ASP.NET CORE Identity

Identity User
Identity Role (Admin)
Password Rules
Cookie Rules

- [ ] Task 4: Implement a “Remember me” checkbox.
- [ ] Task 5: Implement an Authorization API.

Identity Endpoints
Authorize Roles
- [ ] Task 6: Implement an Identity database.
Connect to a remote MySql service

# Test Cases:
### Steps:
Create a mock user
Attempt to login using the correct email address but incorrect password.
### Expected Results: 
The login fails and the account gets locked out.

### Prerequisites:
“Remember me” checkbox is present
User has valid credentials.
### Steps:
Enter valid admin user credentials.
Select the “Remember me” checkbox.
Submit the form, press “Login”.
Clear the browser to end the session.
Reopen browser and reopen the application.
### Steps:
Create a mock user.
Attempt to login with correct credentials.
### Expected Results:
The user is logged in with a success message.

### Steps:
Create a mock user.
Attempt to login with false credentials.
### Expected Results:
The user is logged in with a success message.

# Activity Diagram:
