### ISSUE TITLE
As a customer I want to be able to log in to the system securely so I can access my account features.

### ISSUE THREAD

**Issue by KimmoKAhola** [KYH-Net23/AuthenticationService#5]
Authors: Kimmo Ahola & Isabel Haataja

# Acceptance Criteria:
- [x] There needs to be a login button in the navbar.
- [x] There needs to be a login form.
- [x] There needs to be an authentication process to check credentials.
- [x] There should be a remember me option for future login sessions (cookies).
- [x] Customers should login with an email address and a password.

# Tasks:
- [x] KYH-Net23/Rika#108
- [x] KYH-Net23/Rika#110
- [x] #7
- [x] KYH-Net23/Rika#112
- [x] #8
- [x] KYH-Net23/TokenService#2
- [x] KYH-Net23/Rika#177
- [x] KYH-Net23/IdentityUserService#13

# Test Cases:
### Steps:
- [x] Create a mock user
- [x] Attempt to login using the correct email address but incorrect password.
### Expected Results: 
- [x] The login fails and the account gets locked out.

### Prerequisites:
- [ ] “Remember me” checkbox is present
- [ ] User has valid credentials.
### Steps:
- [ ] Enter valid customer user credentials.
- [ ] Select the “Remember me” checkbox.
- [ ] Submit the form, press “Login”.
- [ ] Clear the browser to end the session.
- [ ] Reopen browser and reopen the application.
Expected Results: 
- [ ] The customer remains logged in.

### Steps:
- [x] Create a mock user.
- [x] Attempt to login with correct credentials.
### Expected Results:
- [x] The user is logged in with a success message.

# Activity Diagram: ![Image](https://github.com/user-attachments/assets/a9f71b66-278e-4949-bd5b-b41355252284)
