### ISSUE TITLE
As an admin I want to be able to log in to the system securely so that I can access administrative features and manage the application effectively.

### ISSUE THREAD

**Issue by KimmoKAhola** [KYH-Net23/AuthenticationService#6]
Authors: Kimmo Ahola & Isabel Haataja

# Acceptance Criteria:
- [x] There needs to be a login button in the navbar.
- [x] Customers and admins login on the same page.
- [x] There needs to be a login form.
- [x] There needs to be an authentication process to check credentials.
- [x] There should be a remember me option for future login sessions (cookies).
- [x] The admin should be locked out after 3 failed attempts if the password entered is incorrect but the email is correct.
- [x] Admin should login with an email address and a password.

# Tasks:
- [x] KYH-Net23/Rika#97
- [x] KYH-Net23/Rika#98
- [x] KYH-Net23/IdentityUserService#1
- [x] KYH-Net23/Rika#99
- [x] KYH-Net23/AuthenticationService#7
- [x] KYH-Net23/IdentityUserService#2
- [x] KYH-Net23/TokenService#1
- [x] KYH-Net23/IdentityUserService#17
- [x] KYH-Net23/Rika#178
- [x] KYH-Net23/IdentityUserService#12

# Test Cases:
### Steps:
- [x] Create a mock user
- [x] Attempt to login using the correct email address but incorrect password.
### Expected Results: 
- [x] The login fails and the account gets locked out.

### Prerequisites:
- [ ] “Remember me” checkbox is present
- [ ] User has valid credentials.
### Steps:
- [ ] Enter valid admin user credentials.
- [ ] Select the “Remember me” checkbox.
- [ ] Submit the form, press “Login”.
- [ ] Clear the browser to end the session.
- [ ] Reopen browser and reopen the application.
### Expected Results: 
- [ ] The admin remains logged in.

### Steps:
- [x] Create a mock user.
- [x] Attempt to login with correct credentials.
### Expected Results:
- [x] The user is logged in with a success message.

### Steps:
- [x] Create a mock user.
- [x] Attempt to login with false credentials.
### Expected Results:
- [x] The login fails.

# Activity Diagram:

![Image](https://github.com/user-attachments/assets/eead67b6-bb15-4f47-a2a8-623fe0ac75f7)

**Comment by Milles98** [comment]
Updated test case 4, it said result: "The user is logged in with a success message."

Changed to:

"The login fails"
